= ドット絵とは

ドット絵（Pixel Art）と呼ばれるものは、いったいどのようなものでしょうか？実は、ドット絵には厳密な定義は存在しません。しかし、現実にはある種の絵を指して「ドット絵」と呼ばれています。われわれは一体どのような絵を「ドット絵」と呼んでいるのでしょうか？

なお、本節はおそらく小難しいことが記述されているので、読み飛ばしていただいてもかまいません。

== あなたがドット絵だと思うものがドット絵

ある人が「ドット絵」と考えるものは、別の誰かにとっては「ドット絵ではない」と捉えられることがあります。

さて、みなさんのとって下記はドット絵でしょうか？

* イラストを縮小し16色に減色したイラスト
* jpgで保存されたドット絵
* 3Dブロックを用いて描かれた絵
* 正方形で構成されたベクターイラスト
* 色付き付箋紙で描かれた絵

おそらく、上記の全てがドット絵ではないと答える人もいるでしょうし、逆に全てがドット絵だと考える人もいるでしょう。もしくは、これはドット絵ではないけど「ドット絵風」だと答える人もいるかもしれません。ドット絵の厳格な定義がない以上、どの主張も正しいとはいえないし、誤っていると断じることもできません。

では、どうすればいいのでしょうか？惑わされてしまった人もいるかもしれませんが、あまり難しく考えることはありません。「あなたがドット絵だと思うものがドット絵」でよいのです。

おそらく、あなたが本書をよんでいるということは、何らかの「ドット絵」と呼ばれるものに感銘を受け、ドット絵を描こうと思ったことでしょう。いや、ゲームが好きなあなたがゲームを作ろうと作ろうと奮い立ち、ゲームを作るために必要なドット絵を描けるようになりたいと思っているのかもしれません。いずれにせよ、あなたは既に「ドット絵」と呼ばれるものを見知っており、頭のなかにドット絵のイメージが有るはずです。それが、あなたの「ドット絵」です。

もし、自分の中の「ドット絵」のイメージが薄いと思うのであれば、インターネットで「ドット絵」や「Pixel Art」などと検索してみるといいでしょう。そこには多くの「ドット絵」ー（と、多くの人が考えているもの）が存在しているはずです。多くドット絵を見ていくうちに、きっとあなたの中で「ドット絵」という概念がより強く形成されていくことでしょう。

== ドット絵の「絵柄」と「技法」

ドット絵について語る場合、ドット絵の「絵柄」とドット絵の「技法」を分けて考える必要があります。前述のとおり、ドット絵そのものの厳密な定義は存在しないため、ドット絵の絵柄と技法もまた厳密に定義できるものではありませんが、筆者は下記のように考えています。

ドット絵の絵柄::
ドット絵と呼ばれている絵に近しい見た目の絵
ドット絵の技法::
ドット絵の絵柄を実現するための技術・方法

単にドット絵と表記されている場合でも、文脈によってドット絵の「絵柄」を指す場合と、ドット絵の「技法」を指す場合とでそれぞれありえます。

== ドット絵の絵柄の特徴

ドット絵の絵柄とはどのようなものでしょうか？一口にドット絵の絵柄といっても、さらにその中でも様々な絵柄が存在するため、一概に語れるわけではありません。それでも、大雑把に言って下記のような特徴が見られます。

* コンピュータやゲーム機等のディスプレイ装置上で表現される
* ディスプレイ上の画素（ピクセル）の集まりで絵が構成されている
* 絵を構成する色の種類が少ない

これらはドット絵と呼ばれる絵におおむね共通する特徴であって、ドット絵の定義ではありません。そのため、上記のいずれかを満たさない絵であってもドット絵ではないと言い切ることはできないことに注意してください。

たとえば、1つ目の特徴としてディスプレイ装置上に表現されるとありますが、ディスプレイ上で表現されない絵でも場合によってはドット絵と呼ぶ人もいることでしょう。

== デジタル画像としてのドット絵

デジタル画像とドット絵とは密接な関係があります。デジタル画像とは、かいつまんで説明するとPC等のデジタル機器上で表現される画像のことです。デジタル画像も広い意味をもつ言葉ですが、ドット絵はデジタル画像として下記のような特徴を持ちます。

* ラスターイメージである
* インデックスカラーの画像形式である

本書では上記の特徴について詳しい説明はしませんが、それぞれ「2次元上に色のついたピクセルを並べている」「色の情報をパレットで取り扱う」ぐらいの認識でよいでしょう。

もちろん、これはただの特徴であって定義ではないので、ベクターイメージのドット絵も実現できるでしょうし、インデックスカラーではなくフルカラー形式のドット絵も存在するでしょう。

ちなみに、2015年現在、ドット絵画像のファイル形式としてはpngまたはgif形式が主流となっています。いずれもRGBカラー256色までのパレットを保有できるファイル形式です。そのため、ほとんどのドット絵はRGBで256色以内の画像として描かれていることでしょう。ただ、これはデジタル画像のファイル形式としての制約ですので、色空間がRGBではないドット絵も存在しうるでしょうし、256色を超過したドット絵も存在しえます。

== 本書で取り扱うドット絵

本書では、特に液晶ディスプレイ上に描画されたデジタル画像のドット絵の絵柄を想定しています。これは本来ドット絵という言葉が持つ意味よりも狭義のドット絵です。そして、そのような狭義のドット絵を描くための技法を取り扱います。デジタル画像としてのファイル形式も標準的なpng/gifで保存されたドット絵を想定しています。

狭義のドット絵に関する技法ではありますが、おおむねより広い意味のドット絵にも同様に役に立つことはあると考えています。たとえば本書は「3Dブロックを用いて描かれた絵」や「色付き付箋紙で構成された絵」などのの見た目を向上させることを考慮していません。しかし、それらの絵にも同じようなアンチパターンが適用できるかもしれませんし、できないかもしれません。

== とりあえず描きたいと思ったドット絵を描こう

ここまで、どうもいきなり小難しく読者を戸惑わせるようなことを書いてしまったかもしれません。

自分にとってのドット絵とは何か？と考えることはとても重要なことなので、あえて最初に「ドット絵とはなにか？」について記述しました。
とはいえ、最初のうちはあまりそのようなことを深く考える必要はないでしょう。

多くのドット絵描きは、たくさんのドット絵を見て、描いています。見て、描く中で、自分たちの中でドット絵というものは何か、というイメージを自分の中でできるものだとおもいます。
難しいことは考えずに、とりあえず描きたいと思ったドット絵というものを描いてみるのが一番よいでしょう。特にはじめのうちは、考えるのは描いてみてからで遅くありません。
