= アンチパターンとは

== アンチパターンの定義

本書を読む方は、link:https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%B3%E3%83%81%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3[アンチパターン]という用語を聞き慣れない人も多いかと思います。アンチパターンは、元はソフトウェア工学の分野で提唱された用語です。

アンチパターンとは、ある問題を解決するための不適切な解決策を類型化したものです。アンチパターンを整理することにより、同様な事例を早期に発見することができます。さらに、不適切な解決策に対する適切な解決策を提案しています。

アンチパターンは、単純に悪い例というわけではなく、下記のような性質を持ちます。

. 最初は良い解決策とおもわれるが、最終的には悪い結果をもたらす
. 改善するための一般的な方法が明示されている

小難しい厳密な定義はさておき、簡単に言うと初学者がよく陥る悪い典型例のようなものだと思っておけばよいでしょう。

NOTE: アンチパターンと聞くと、ドット絵に慣れ親しんている方はアンチエイリアスのパターンと連想してしまうかもしれません。ドット絵において単に「アンチ」といった場合、それはアンチエイリアスを指すからです。しかし、本書では紛らわしいため、アンチエイリアスのことはアンチとは省略しません。アンチエイリアスはアンチエイリアス、アンチパターンはアンチパターンと表記します。

== ドット絵におけるアンチパターン

2015年現在ではあまり見られなくなりましたが、Web上では掲示板でドット絵指南といった活動がよく行われていました（今も一部で行われてはいます）。そこでは、ある人が描いたドット絵を別の人が見てよりよく描くにはどうしたらよいのか、教えてもらうことができます。特に、ドット絵にまだ慣れ親しんでいない初心者のうちは、ドット絵指南の場で熟練者に指摘を受けたほうが、より早く上達することもあるでしょう。

ドット絵の指南内容を多く見ていると、似たような指摘も多いことに気が付きます。特に、ドット絵初心者が描くドット絵はある程度のパターンがあり、指摘の内容もたいていは似たりよったりだったりします。そのような、初心者がよく陥りがちな描き方と、それに対する指摘の内容を類型化したものが、本書ドット絵アンチパターンの内容といえます。

== ドット絵のアンチパターンの例外

ドット絵アンチパターンにあてはまるドット絵は、すべて悪いドット絵と思ってしまう方がいるかもしれません。しかし、アンチパターンに当てはまるからといって、悪いドット絵とは限らないことに注意してください。

ドット絵も絵なので、最終的な良し悪しは人間がその絵を良いと思うかどうかによります。つまり、ある人は良いと思う絵であっても、別のある人にとっては悪いと感じることがあるかもしれません。絵を感じるのは人間の主観なので、当然のことです。

ドット絵の良し悪しは人によるため、あなたの絵がアンチパターンに当てはまるからといって、必ずしも悪い絵とは限りません。ドット絵のアンチパターンには常に例外がありえます。あなたがその描き方が良いと信じるならば、アンチパターンの解決策を実施する必要はありません。最終的には、どのような描き方をするか選ぶのはあなた自身です。
