= ドット絵とは

ドット絵（Pixel Art）と呼ばれるものは、いったいどのようなものでしょうか？実は、ドット絵には厳密な定義は存在しません。しかし、現実にはある種の絵を指して「ドット絵」と呼ばれています。われわれは一体どのような絵を「ドット絵」と呼んでいるのでしょうか？

なお、本節はおそらく小難しいことが記述されているので、読み飛ばしていただいてもかまいません。

== あなたがドット絵だと思うものがドット絵

ある人が「ドット絵」と考えるものは、別の誰かにとっては「ドット絵ではない」と捉えられることがあります。

さて、みなさんのとって下記はドット絵でしょうか？

* イラストを縮小し16色に減色したイラスト
* jpgで保存されたドット絵
* 3Dブロックを用いて描かれた絵
* 正方形で構成されたベクターイラスト
* 色付き付箋紙で描かれた絵

おそらく、上記の全てがドット絵ではないと答える人もいるでしょうし、逆に全てがドット絵だと考える人もいるでしょう。もしくは、これはドット絵ではないけど「ドット絵風」だと答える人もいるかもしれません。はたまた、16色以内で描かれた低解像度のゲーム用イラストでなければドット絵ではないと考えている人もいるでしょう。ドット絵の厳格な定義がない以上、どの主張も正しいとはいえないし、誤っていると断じることもできません。

では、どうすればいいのでしょうか？惑わされてしまった人もいるかもしれませんが、あまり難しく考えることはありません。「あなたがドット絵だと思うものがドット絵」でよいのです。

おそらく、あなたが本書をよんでいるということは、何らかの「ドット絵」と呼ばれるものに感銘を受け、ドット絵を描こうと思ったことでしょう。いや、上司からの業務命令でドット絵というものについて調べている最中かもしれません。はたまた、ゲームが好きなあなたがゲームを作ろうと作ろうと奮い立ち、ゲームを作るために必要なドット絵を描けるようになりたいと思っているのかもしれません。いずれにせよ、あなたは既に「ドット絵」と呼ばれるものを見知っており、頭のなかにドット絵のイメージが有るはずです。それが、あなたの「ドット絵」です。

もし、自分の中の「ドット絵」のイメージが薄いと思うのであれば、インターネットで「ドット絵」や「Pixel Art」などと検索してみるといいでしょう。そこには多くの「ドット絵」ー（と、多くの人が考えているもの）が存在しているはずです。多くドット絵を見ていくうちに、きっとあなたの中で「ドット絵」という概念がより強く形成されていくことでしょう。

== ドット絵の「絵柄」と「技法」

ドット絵について語る場合、ドット絵の「絵柄」とドット絵の「技法」を分けて考える必要があります。前述のとおり、ドット絵そのものの厳密な定義は存在しないため、ドット絵の絵柄と技法もまた厳密に定義できるものではありませんが、筆者は下記のように考えています。

ドット絵の絵柄::
ドット絵と呼ばれている絵に近しい見た目の絵
ドット絵の技法::
ドット絵の絵柄を実現するための技術・方法

単にドット絵と表記されている場合でも、文脈によってドット絵の「絵柄」を指す場合と、ドット絵の「技法」を指す場合とでそれぞれありえます。

== ドット絵の絵柄の特徴

ドット絵の絵柄とはどのようなものでしょうか？一口にドット絵の絵柄といっても、さらにその中でも様々な絵柄が存在するため、一概に語れるわけではありません。それでも、大雑把に言って下記のような特徴が見られます。

* コンピュータやゲーム機等のディスプレイ装置上で表現される
* ディスプレイ上の画素（ピクセル）の集まりで絵が構成されている
* 絵を構成する色の種類が少ない

これらはドット絵と呼ばれる絵におおむね共通する特徴であって、ドット絵の定義ではありません。そのため、上記のいずれかを満たさない絵であってもドット絵ではないと言い切ることはできないことに注意してください。

たとえば、1つ目の特徴としてディスプレイ装置上に表現されるとありますが、ディスプレイ上で表現されない絵でも場合によってはドット絵と呼ぶ人もいることでしょう。

== デジタルゲームとドット絵

ドット絵はその発展の経緯から、デジタルゲームと深い結びつきがあります。ドット絵黎明期の発展の歴史は、デジタルゲーム黎明期の発展の歴史と共にありました。ちなみに、デジタルゲームというと広い言葉ですが、有名なもので言えばスペースインベーダーであったり、MSXであったり、ファミリーコンピューターであったり、PlayStationであったり、そういったアーケードやPCやゲーム機などで遊べるゲームの総称です。

黎明期のデジタルゲームは、ゲームを動かすハードウェアの制約がたいへん大きいものでした。例えば、画面全体やスプライト単位の解像度が低かったり、特定の色のうち一定数の色しか使用できなかったりといったことです。しかし、そのようなハードウェアの制約がある中で、より美しい絵を描画することを目指すことで、ドット絵と呼ばれる絵柄が育ってきたといえます。描画上の制約そのものはそのハードウェアに依存します（link:https://en.wikipedia.org/wiki/List_of_color_palettes[Wikipedia: List of color palettes]などを見ると各種ハードウェアの制約がわかりやすいでしょう）。そして、ハードウェアが進化し制約が緩くなっていくに従って、ドット絵の絵柄もハードウェアの制約に合わせて変化していきました。

2015年現在ではゲーム機やPCの性能は過去とは比べ物にならないほど向上し、絵を描く上でハードウェア上の制約を気にすること無く自由に絵を描くことができるようになりました（制約が皆無ではありませんが、通常その制約を意識することはまずないでしょう）。ハードウェア上の制約が無くなってくると、その中でより美しい絵を描画しようとしたとき、より多様な絵柄が存在することになります。いまでは、黎明期のデジタルゲーム機と共に発展してきたドット絵の絵柄と比べると大きくかけ離れた絵柄も多く見られます。むしろ、現代ではドット絵の絵柄を選択することは相対的に少なくなっているでしょう。また、基本的に人間が1ピクセル単位で描画するドット絵の技法からしても、大きな解像度のなかで美しい描くことはたいへん難しく、開発効率上も非効率です。現在の環境であればグラフィックソフトで普通に大きなイラストを描いてそのまま利用したり、または3Dを活用した高度な計算を下支えとした描写などを選択することができます。ドット絵とは異なる、新しい技術を活用した新しい絵柄も次々と産み出されています。

しかし、ハードウェア上の制約がほぼ無くなった現在でも、少ないとはいえドット絵の絵柄のゲームもまた新しく産み出されてもいます。それはいったいなぜでしょうか？ドット絵を描く理由は人や目的によってそれぞれあることでしょう。ハードウェアの制約がない今、なぜ他の方法ではなくドット絵で描こうとするのか、是非あなた自身で考えて、答えを持っておくとよいかもしれません。

== デジタル画像としてのドット絵

デジタル画像とドット絵とは密接な関係があります。デジタル画像とは、かいつまんで説明するとPC等のデジタル機器上で表現される画像のことです。デジタル画像も広い意味をもつ言葉ですが、ドット絵はデジタル画像として下記のような特徴を持ちます。

* ラスターイメージである
* インデックスカラーの画像形式である

本書では上記の特徴について詳しい説明はしませんが、それぞれ「2次元上に色のついたピクセルを並べている」「色の情報をパレットで取り扱う」ぐらいの認識でよいでしょう。

もちろん、これはただの特徴であって定義ではないので、ベクターイメージのドット絵も実現できるでしょうし、インデックスカラーではなくフルカラー形式のドット絵も存在するでしょう。

ちなみに、2015年現在、ドット絵画像のファイル形式としてはpngまたはgif形式が主流となっています。いずれもRGBカラー256色までのパレットを保有できるファイル形式です。そのため、ほとんどのドット絵はRGBで256色以内の画像として描かれていることでしょう。ただ、これはデジタル画像のファイル形式としての制約ですので、色空間がRGBではないドット絵も存在しうるでしょうし、256色を超過したドット絵も存在しえます。

== 本書で取り扱うドット絵

本書では、特に液晶ディスプレイ上に描画されたデジタル画像のドット絵の絵柄を想定しています。これは本来ドット絵という言葉が持つ意味よりも狭義のドット絵です。そして、そのような狭義のドット絵を描くための技法を取り扱います。デジタル画像としてのファイル形式も標準的なpng/gifで保存されたドット絵を想定しています。

狭義のドット絵に関する技法ではありますが、おおむねより広い意味のドット絵にも同様に役に立つことはあると考えています。たとえば本書は「3Dブロックを用いて描かれた絵」や「色付き付箋紙で構成された絵」などのの見た目を向上させることを考慮していません。しかし、それらの絵にも同じようなアンチパターンが適用できるかもしれませんし、できないかもしれません。

== とりあえず描きたいと思ったドット絵を描こう

ここまで、どうもいきなり小難しく読者を戸惑わせるようなことを書いてしまったかもしれません。

自分にとってのドット絵とは何か？と考えることはとても重要なことなので、あえて最初に「ドット絵とはなにか？」について記述しました。
とはいえ、最初のうちはあまりそのようなことを深く考える必要はないでしょう。

多くのドット絵描きは、たくさんのドット絵を見て、描いています。見て、描く中で、自分たちの中でドット絵というものは何か、というイメージを自分の中でできるものだとおもいます。
難しいことは考えずに、とりあえず描きたいと思ったドット絵というものを描いてみるのが一番よいでしょう。特にはじめのうちは、考えるのは描いてみてからで遅くありません。
