= ドット絵技法の基礎知識

アンチパターンを学ぶ前に前提となるドット絵技法の基礎知識を簡単に解説します。本書はドット絵技法の基礎解説を目的としていませんので、必要最小限の解説となっています。より詳細なドット絵技法についてはドット絵プロフェッショナルテクニックなどの他の文献を参照してください。

== ピクセル

ドット絵はピクセル（Pixel）を基本単位として描画されます。ピクセルは「画素」「ドット」「点」などとも呼ばれます。ドット絵の「ドット」とはこの基本単位を指します。

本書中での表記はすべてピクセルに統一します。

== パレット

パレットとはドット絵が保持している使用可能色の集まりです。主要な画像形式では256色以内の色数となっている場合が多くなっています。デジタル画像の用語としては、このようにパレットを保持している画像はインデックスカラー画像と呼ばれます。

== アンチエイリアス

ドット絵は低解像度の絵のため、絵柄にもよりますがギザギザした見た目になります。このギザギザはエイリアシング（Ailiasing）と呼ばれます。このエイリアシングによる見た目のギザギザを低減させるようにピクセルを配置することを、アンチエイリアス（Anti Ailiasing）といいます。

デジタル画像に関するエイリアシングはジャギー（Jaggy）とも呼ばれ、日本ではアンチエイリアスのことをジャギ消しと呼ぶこともあります。また、Web上ではアンチエイリアスの省略形として「アンチ」や「AA（**A**nti **A**iliasingの略）」などと表記されることもあります。

本書中での表記はすべてアンチエイリアスに統一します。

== RGB

表色系の一種で、色を光の三原色である赤（Red）緑（Green）青（Blue）の三要素による色の表現方法です。

2015年現在、ドット絵においては、24ビットカラーのRGBで描かれる場合がほとんどです。24ビットカラーのRGBとは、赤・緑・青それぞれに8ビットの情報をもつRGBです（8ビット×3 = 24ビット）。8ビットでは256段階の情報を保持できます。つまり、赤・緑・青の256段階の組み合わせにより、256×256×256=16,777,216通りの異なる色を表現することができる方式です。

ただし、ドット絵はRGBで描かれるものとは限らないので、注意してください（たとえば、ファミコンはRGBではない）。

本書では、現在一般的な24ビットカラーのRGBで描かれたドット絵を想定しています。
